### ISSUE TITLE
Discover doesn't raise Exception or else when ble adapter is diasbled

### ISSUE THREAD

**Issue by pawelm87** [hbldh/bleak#355] opened 2020-10-31 18:31 UTC
* bleak version: 0.9.1
* Python version: 3.8.6
* Operating System: Win10
* BlueZ version (bluetoothctl -v) in case of Linux: -

### Description

How to get the feedback that the ble adapter is disabled at laptop with Win10 when try discover devices. When I explored the discover function I don't found Exception. In the discover function for Linux is Exception :
`raise Exception("Bluetooth adapter not found")`
but not inWindows discover. I want got feedback and stop execute script when adapter is off. 

### What I Did

Turnoff adapter bluetooth in the setting at windows 10 and run example discover script. The script does not found any device, and stop without any error.
```
import asyncio
from bleak import discover

async def run():
    try:
        devices = await discover(timeout=10)
    except Exception as e:
        print(e)
    for d in devices:
        print(d)


loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(run())
except Exception as e:
    print(e)
```

**Comment by dlech** [comment] 2020-10-31 20:10
Closing as duplicate of #320. Please leave any further comments there.

**Closed by dlech** 2020-10-31 20:10 UTC
Labels: duplicate
