### ISSUE TITLE
Should BleakGATTCharacteristic.description honour a 2901 descriptor

### ISSUE THREAD

**Issue by jackjansen** [hbldh/bleak#1066] opened 2022-10-05 21:21 UTC
At the moment `BleakGATTCharacteristic.description` simply returns `uuidstr_to_str(self.uuid)`.

I have the feeling it would be better if it also catered for a 2901 descriptor on the characteristic, if available.

Whether the 2901 should take precedence over the database or the other way around: I'm not sure, there's something to be said for either order.

**Comment by dlech** [comment] 2022-10-06 16:26
Duplicate of #908.

**Closed by dlech** 2022-10-06 16:26 UTC
Labels: duplicate
