### ISSUE TITLE
bleak android error

### ISSUE THREAD

**Issue by ps2229** [hbldh/bleak#821] opened 2022-05-02 13:24 UTC
* bleak version:0.14.2
* Python version:3
* Operating System:android
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

 Trying to implement bleak start_notify function

### What I Did
     async def begin_scan1(self):
        async def callback2(sender: int, data: bytearray):
            print(sender, data,'llllll')
        a = []
        scanned_devices = await bleak.BleakScanner.discover(1)

        if len(scanned_devices) == 0:
            print("NO DEVICES")
        scanned_devices.sort(key=lambda device: -device.rssi)
        for device in scanned_devices:
            device1 = f"{device.name}"
            print(device1)
            if device1 == "Bluno":
                try:
                    async with bleak.BleakClient(device) as client:
                        print('rr')
                        paired = client.pair(protection_level=2)
                        print(f"Paired: {paired}")
                        COLOR_CHARACTERISTIC = "0000dfb1-0000-1000-8000-00805f9b34fb"
                        uu = '1'
                        write_value = bytearray([int(uu)])
                        await client.write_gatt_char(COLOR_CHARACTERISTIC, write_value) 
                        print('www')
                        await client.start_notify(COLOR_CHARACTERISTIC, callback2)
                        print('wwee')
                        await asyncio.sleep(10.0)
                        print('rrrq')
                        await client.stop_notify(COLOR_CHARACTERISTIC)
                   
                except:

                    asyncio.sleep(10)
                    toast('error')
                    self.main_pop.dismiss()
            else:
                toast('Device Not Found', duration=1)
                self.main_pop.dismiss()
        self.main_pop.dismiss()
Was getting error bleak.exc.bleakerror:descriptor None was not found.
Any clue why I am getting this issue or how to solve it.

**Comment by dlech** [comment] 2022-07-13 20:15
Duplicate of #828.

**Closed by dlech** 2022-07-13 20:15 UTC
