### ISSUE TITLE
set_disconnected_callback not supported on CoreBluetooth?

### ISSUE THREAD

**Issue by niemyjski** [hbldh/bleak#190] opened 2020-05-14 15:10 UTC
* bleak version: latest
* Python version: 3.8
* Operating System: macOS Latest
* BlueZ version (`bluetoothctl -v`) in case of Linux: 

### Description

Unable to set disconnected callback on macOS.

### What I Did

```
def onDisconnect(client):
    print("Client with address {} got disconnected!".format(client.address))

async with BleakClient(device.address, loop=loop) as client:
        try:
            client.set_disconnected_callback(onDisconnect)
```

**Comment by dlech** [comment] 2020-05-14 16:08
Duplicate of #184?

**Comment by hbldh** [comment] 2020-05-15 07:18
You are should be unable to do this right now and bleak should throw a `NotImplementedError` with the text `"This is not implemented in the Core Bluetooth backend yet"` which should tell you everything you need to know.

Apart from that, a PR implementing this is in the works: #186

**Closed by hbldh** 2020-05-15 07:18 UTC
