### ISSUE TITLE
client connect error 

### ISSUE THREAD

**Issue by profff** [hbldh/bleak#1078] opened 2022-10-13 10:53 UTC
* bleak version:
bleak                0.18.1
bleak-winrt          1.2.0
* Python version:
Python 3.10.6
* Operating System:
* Windows 10 Professionnal x64

### Description

try to conneect to a device for listing services 
BleakScanner is working great but connect BleakClient end on error at connect if the device is not already bonded to host
if it's bonded it's working great 
 

### What I Did
heres my code 
```python
import asyncio
import sys
from bleak import BleakScanner,BleakClient
import platform

def searchDeviceByName(name):
	# looks after infbs devs
	infbs_devs=[]
	all_devs=[]
	async def run():
	    devices = await BleakScanner.discover()
	    for d in devices:
	    	all_devs.append(d)
	    	if d.name==name: 
	    		infbs_devs.append(d)
	asyncio.run(run())
	if(len(infbs_devs)<1):
		print("no "+name+" devices found")
		for d in all_devs: 
			print(d)
		return(0)
	# if only one dev found go ehead else let choose what dev to go with 
	if(len(infbs_devs)>1):
		i=0
		for d in infbs_devs: 
			print(i,"-",d)
		i=int(input("whitch one ? : "))
		dev=infbs_devs[i]
	else:
		dev=infbs_devs[0]
	return(dev)

dev=searchDeviceByName("INF-BS")
if dev==0:	
	exit()
	
print("connecting to : ",dev)
async def main(dev):
    async with BleakClient(dev.address) as client:
        print("Services:")
        for service in client.services:
            print(service)
asyncio.run(main(dev))
```
heres error that are are returned at execution 

```C:\src\btserial> python .\btserial.py
connecting to :  62:51:3E:39:74:DE: INF-BS
Traceback (most recent call last):
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 331, in connect
    await event.wait()
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\btserial\btserial.py", line 44, in <module>
    asyncio.run(main(dev))
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\src\btserial\btserial.py", line 40, in main
    async with BleakClient(dev.address) as client:
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\__init__.py", line 354, in __aenter__
    await self.connect()
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\__init__.py", line 392, in connect
    return await self._backend.connect(**kwargs)
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 330, in connect
    async with async_timeout.timeout(timeout):
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\site-packages\async_timeout\__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "C:\Users\o.gaste\AppData\Local\Programs\Python\Python310\lib\site-packages\async_timeout\__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError```
 
### Logs
unfortunatly I got error when trying to launch BTP

**Comment by dlech** [comment] 2022-10-13 15:37
First of all, this program calls `asyncio.run()` twice, so that is going to cause problems (move everything into the `main()` function to fix it).

Second, this sounds like a duplicate of #604 and #809 - both of which are still waiting for someone to capture bluetooth packets.

**Closed** 2022-10-27 07:42 UTC
Labels: Backend: WinRT
