### ISSUE TITLE
"Could not get GATT services: Unreachable" when try to connect 

### ISSUE THREAD

**Issue by IcyChlorine** [hbldh/bleak#820] opened 2022-05-01 07:58 UTC
* bleak version: v1.14.3 with bleak-winrt v1.1.1
* Python version: 3.7.2(which I suppose is not important here)
* Operating System: Win10
* remote environment: ESP32, micropython v1.18

### Description

I made a GATT server on ESP32 board implementing Nordic UART service. It can be correctly connected from phone via "Serial Bluetooth Terminal" software, but when I use bleak to connect, error occors.

Error Traceback is like:
```
...
client.py 276 connect
await self.get_services()

client.py 456 get_services
"Could not get GATT services",

bleak.exc.BleakError:
Could not get GATT services: Unreachable
```

Seems bleak can't get GATT services. But I checked twice that 1)I had registered services on ESP32 software properly and 2)It can be correctly connected via my bluetooth debugging software on cell phone.

I'm not sure if its a bug of `bleak` or it's because I've implemented the GATT server on ESP32 wrongly?

### What I Did
The desktop code(gatt client) I use is from the example of bleak: `bleak/examples/uart_service.py`
The code I use on my ESP32 board is almost identical from the DEMO code in this website: [https://techtotinker.blogspot.com/2021/08/025-esp32-micropython-esp32-bluetooth.html](https://techtotinker.blogspot.com/2021/08/025-esp32-micropython-esp32-bluetooth.html)

I've been stucking on the problem for quite some days, and I would really appreciate some guidance! /(ㄒoㄒ)/~~

**Comment by dlech** [comment] 2022-07-13 20:19
duplicate of #740

**Closed by dlech** 2022-07-13 20:19 UTC
Labels: Backend: WinRT
