### ISSUE TITLE
Timeout for discover in connect()

### ISSUE THREAD

**Issue by skjerns** [hbldh/bleak#75] opened 2019-06-13 10:22 UTC
* bleak version: 0.4.2
* Python version: 3.7
* Operating System: Win10

### Description

When connecting via DotNet backend, `discover` is called with a timeout of `2.0`. However, this timeout is not always sufficient to get responses from the device necessary. In around 1/3rd of the cases it will not be able to connect to my device due to not finding it within 2 seconds.

Do you think that here a 'continue looking for device until found or timeout' loop would be useful? So the maximal timeout would be the default `5.0`, but it can be shorter if the device is found before. Else, the connect method might have a parameter `force` that also tries to connect even if the device was not found during radio?

**Comment by hbldh** [comment] 2019-06-24 09:14
Duplicate of #70.
This is fixed in  6daae16 and will be released in version 0.4.3 shortly.

**Closed** 2019-06-30 21:03 UTC
Labels: .NET, duplicate, enhancement

**Comment by hbldh** [comment] 2019-07-01 08:20
Released 0.4.3 yesterday. Timeout keyword is now available in both BlueZ and .NET backend.
