### ISSUE TITLE
Cannot discover ble devices on macOS Monterey.

### ISSUE THREAD

**Issue by jha929** [hbldh/bleak#765] opened 2022-02-15 05:56 UTC
* bleak version: 1.13.0
* Python version: 3.7.11
* Operating System: macOS `Monterey`

### Description
Trying to list all BLE devices using https://github.com/hbldh/bleak/blob/develop/examples/discover.py and had no luck.

### What I Did
Ran the python script below:
```python
import asyncio
from bleak import discover

async def main():
    devices = await discover()
    for d in devices:
        print(d)

if __name__ == "__main__":
    asyncio.run(main())
```

And nothing has been printed out.

I'm curious if anyone else facing a similar issue in `macOS Monterey`?

Thanks in advance.

**Comment by dlech** [comment] 2022-02-15 14:55
If you update to Bleak 0.14.x, there will be an error message logged explaining the issue. Duplicate of #635 and #720.

**Closed by dlech** 2022-02-15 14:55 UTC
