### ISSUE TITLE
Device may already be connected when calling connect with BlueZ

### ISSUE THREAD

**Issue by bdraco** [hbldh/bleak#992] opened 2022-09-10 02:42 UTC
If the device is connected, and then the application/docker container is restarted and the device is not disconnected, the next connection attempt will fail because the device is already connected on the host but we think it is not connected and a connect call will fail.

```
      "/org/bluez/hci1/dev_BD_24_6F_85_AA_61": {
        "org.freedesktop.DBus.Introspectable": {},
        "org.bluez.Device1": {
          "Address": "BD:24:6F:85:AA:61",
          "AddressType": "public",
          "Name": "Dream~BD246F85AA61",
          "Alias": "Dream~BD246F85AA61",
          "Appearance": 962,
          "Icon": "input-mouse",
          "Paired": false,
          "Trusted": false,
          "Blocked": false,
          "LegacyPairing": false,
          "RSSI": -36,
          "Connected": true,
          "UUIDs": [
            "00001800-0000-1000-8000-00805f9b34fb",
            "00001801-0000-1000-8000-00805f9b34fb",
            "0000180a-0000-1000-8000-00805f9b34fb",
            "0000ffd0-0000-1000-8000-00805f9b34fb",
            "0000ffd5-0000-1000-8000-00805f9b34fb"
          ],
          "Modalias": "usb:v045Ep0040d0300",
          "Adapter": "/org/bluez/hci1",
          "ManufacturerData": {
            "20808": {
              "__type": "<class 'bytearray'>",
              "repr": "bytearray(b'364656')"
            }
          },
          "ServicesResolved": true
        },
        "org.freedesktop.DBus.Properties": {}
      },
```

**Comment by bdraco** [comment] 2022-09-10 02:42
Need to think about how to fix this one as its not strait-forward.  I wanted to document it so I don't forget about it

**Comment by bdraco** [comment] 2022-09-10 03:12
Maybe skip calling "Connect" if the `Connected` property is already true when we get here https://github.com/hbldh/bleak/blob/aa24332a39952880005705155629df423fbad1aa/bleak/backends/bluezdbus/client.py#L158

**Comment by bdraco** [comment] 2022-09-10 03:14
Maybe could use the same check that ServicesResolved uses

**Comment by dlech** [comment] 2022-09-10 16:12
This is essentially a duplicate of #367.

Instead of hacking the BleakClient connect method, I think we should use the algorithm described in the diagram [here](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/BestPracticesForInteractingWithARemotePeripheralDevice/BestPracticesForInteractingWithARemotePeripheralDevice.html#//apple_ref/doc/uid/TP40013257-CH6-SW9).

The idea I've had in my mind for a while to do this is to create a new BleakAdapter class. This class could provide the "get known peripherals" and the "get connected peripherals" methods. The BleakAdapter class could also be used to solve issues like #320 and #513.

**Comment by dlech** [comment] 2022-09-10 16:16
Also related is https://github.com/bluez/bluez/issues/89. Bluez is the only OS stack that doesn't "release" the device when the app dies.

**Closed** 2022-09-10 20:54 UTC
